POST http://localhost:3001/api/notes
Content-Type: application/json; charset=utf-8

{
    "content": "VS Code Rest client is pretty good",
    "important": false
}

# Headers: application/json;
# {
#     "body": "hello"
# }
